---
- name: Health Check Basico Linux
  hosts: all
  become: yes
  gather_facts: yes

  tasks:

    - name: Obtener hostname
      command: hostname
      register: hostname

    - name: Obtener uptime
      command: uptime -p
      register: uptime

    - name: Uso de CPU
      shell: "top -bn1 | grep 'Cpu(s)' | awk '{print $2 + $4}'"
      register: cpu_usage

    - name: Uso de memoria
      shell: "free -m | awk 'NR==2{printf \"%.2f\", $3*100/$2 }'"
      register: mem_usage

    - name: Uso de disco
      command: df -h /
      register: disk_usage

    - name: Verificar particiones críticas
      command: df -h
      register: all_disks

    - name: Procesos más pesados (Top 5 CPU)
      shell: "ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%cpu | head -n 6"
      register: top_cpu

    - name: Procesos más pesados (Top 5 Memoria)
      shell: "ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem | head -n 6"
      register: top_mem

    - name: Verificar servicios críticos (ejemplo sshd)
      systemd:
        name: sshd
        state: started
      register: ssh_status

    - name: Verificar puertos abiertos
      shell: "ss -tuln"
      register: open_ports

    - name: Mostrar resultados
      debug:
        msg: |
          ====== HEALTH CHECK ======
          Hostname: {{ hostname.stdout }}
          CPU: {{ cpu_usage.stdout }} %
          Memoria: {{ mem_usage.stdout }} %
    - name: Generar reporte HTML
      copy:
        dest: "/tmp/healthcheck_{{ inventory_hostname }}.html"
        content: |
          <html>
          <body>
          <h2>Health Check - {{ inventory_hostname }}</h2>
          <table border="1">
            <tr>
              <th>CPU %</th>
              <th>Memoria %</th>
              <th>Uptime</th>
            </tr>
            <tr>
              <td>{{ cpu_usage.stdout }}</td>
              <td>{{ mem_usage.stdout }}</td>
              <td>{{ uptime.stdout }}</td>
            </tr>
          </table>
          </body>
          </html>