---
- name: Filesystem Usage Check
  hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Excluir Windows
      meta: end_host
      when: ansible_os_family == "Windows"

  tasks:

    - name: Obtener uso de filesystem
      shell: "df -h --output=source,size,used,avail,pcent,target"
      register: fs_usage

    - name: Mostrar filesystem sin encabezado duplicado
      debug:
        msg: |
          ===== FILESYSTEM USAGE =====
          Host: {{ inventory_hostname }}

          {% for line in fs_usage.stdout_lines[1:] %}
          {{ line }}
          {% endfor %}